version: "3"

services:
  cliapp:
    platform: linux/amd64
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile.cliapp
    depends_on:
      - redis_cache
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=redis_cache

  webapp:
    platform: linux/amd64
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile.webapp
    depends_on:
      - redis_cache
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=redis_cache
    ports:
      - "80:80"

  redis_cache:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'





