version: "3"

services:
  cliapp:
    platform: linux/amd64
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile.cliapp
    volumes:
      - type: volume
        source: shared_cli_data_volume
        target: /opt/chimera/data
  webapp:
    platform: linux/amd64
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile.webapp
    volumes:
      - type: volume
        source: shared_cli_data_volume
        target: /opt/chimera/data
    ports:
      - "80:80"
volumes:
  shared_cli_data_volume:

