FROM ubuntu:xenial
RUN apt-get update && apt-get install -y jq curl
WORKDIR /opt/chimera/bin
RUN curl --fail https://devops-cli-workshop.s3.eu-west-2.amazonaws.com/cliapp --output cliapp
RUN chmod +x cliapp
ENV DATA_FOLDER=/opt/chimera/data
RUN mkdir /var/log/chimera
COPY ./run.sh ./run.sh
RUN chmod +x ./run.sh
ENTRYPOINT ["./run.sh"]